# Copyright (c) 2021-2024 D-Robotics Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


model_parameters:
  onnx_model: './../PaddleOCR/inference/rec_onnx/model_recv3.onnx'
  march: "nash-e"
  layer_out_dump: False
  working_dir: 'model_output'
  output_model_file_prefix: 'cn_PP-OCRv3_rec_infer-deploy_48x320_rgb'
  node_info: {
    "p2o.Softmax.0": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "p2o.Softmax.1": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "p2o.Softmax.2": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    }
  }


input_parameters:
  input_name: ""
  input_type_rt: 'featuremap'
  input_layout_rt: 'NCHW'
  input_type_train: 'featuremap'
  input_layout_train: 'NCHW'
  input_shape: '1x3x48x320'
  norm_type: 'no_preprocess'


calibration_parameters:
  cal_data_dir: './../calibration_data_rec_new/cropped_images_npy'
  cal_data_type: 'float32'
  calibration_type: 'default'
  optimization: "set_all_nodes_int16"


compiler_parameters:
  compile_mode: 'latency'
  debug: False
  optimize_level: 'O2'
  
